// Package apiv1gen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package apiv1gen

import (
	"encoding/json"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for CreateRunRequestStrategy.
const (
	CreateRunRequestStrategyFanout  CreateRunRequestStrategy = "fanout"
	CreateRunRequestStrategyMonitor CreateRunRequestStrategy = "monitor"
	CreateRunRequestStrategyReact   CreateRunRequestStrategy = "react"
	CreateRunRequestStrategyStepDag CreateRunRequestStrategy = "step_dag"
)

// Valid indicates whether the value is a known member of the CreateRunRequestStrategy enum.
func (e CreateRunRequestStrategy) Valid() bool {
	switch e {
	case CreateRunRequestStrategyFanout:
		return true
	case CreateRunRequestStrategyMonitor:
		return true
	case CreateRunRequestStrategyReact:
		return true
	case CreateRunRequestStrategyStepDag:
		return true
	default:
		return false
	}
}

// Defines values for RunStrategy.
const (
	RunStrategyFanout  RunStrategy = "fanout"
	RunStrategyMonitor RunStrategy = "monitor"
	RunStrategyReact   RunStrategy = "react"
	RunStrategyStepDag RunStrategy = "step_dag"
)

// Valid indicates whether the value is a known member of the RunStrategy enum.
func (e RunStrategy) Valid() bool {
	switch e {
	case RunStrategyFanout:
		return true
	case RunStrategyMonitor:
		return true
	case RunStrategyReact:
		return true
	case RunStrategyStepDag:
		return true
	default:
		return false
	}
}

// AgentTask defines model for AgentTask.
type AgentTask struct {
	Name     string  `json:"name"`
	Runner   *string `json:"runner,omitempty"`
	Schedule *string `json:"schedule,omitempty"`
	Strategy *string `json:"strategy,omitempty"`
}

// AgentTaskList defines model for AgentTaskList.
type AgentTaskList struct {
	Items         []AgentTask `json:"items"`
	NextPageToken *string     `json:"nextPageToken,omitempty"`
}

// Approval A pending tool-call approval awaiting a human decision.
type Approval struct {
	// CallId The tool call id; pass it to /approvals/{callId}/resolve.
	CallId     string                  `json:"callId"`
	CreateTime *time.Time              `json:"createTime,omitempty"`
	Input      *map[string]interface{} `json:"input,omitempty"`
	ToolName   *string                 `json:"toolName,omitempty"`
}

// ApprovalList defines model for ApprovalList.
type ApprovalList struct {
	Items         []Approval `json:"items"`
	NextPageToken *string    `json:"nextPageToken,omitempty"`
}

// ApprovalPolicy Session approval policy for a fanout run.
type ApprovalPolicy struct {
	AutoApproveAll   *bool            `json:"autoApproveAll,omitempty"`
	AutoApproveTools *map[string]bool `json:"autoApproveTools,omitempty"`
	DenyTools        *map[string]bool `json:"denyTools,omitempty"`
}

// ApprovalPolicyDelta Additive change to a session approval policy.
type ApprovalPolicyDelta struct {
	AddTools *[]string `json:"addTools,omitempty"`
}

// AuthInfo Whether the server requires a bearer API key.
type AuthInfo struct {
	Required bool `json:"required"`
}

// CreateRunRequest defines model for CreateRunRequest.
type CreateRunRequest struct {
	Agent    *string                   `json:"agent,omitempty"`
	Params   *map[string]interface{}   `json:"params,omitempty"`
	Strategy *CreateRunRequestStrategy `json:"strategy,omitempty"`
}

// CreateRunRequestStrategy defines model for CreateRunRequest.Strategy.
type CreateRunRequestStrategy string

// EventStream A `text/event-stream`. Each frame is an `event: <type>` line plus a
// `data: <json>` line; the two resumable streams (`GET /events`,
// `GET /runs/{run}/events`) also prefix `id: <sequence>`. Parse `data` as
// JSON; its shape depends on the event type:
//
// | event | data fields | meaning |
// | --- | --- | --- |
// | `chunk` | `turnId`, `text` | a streamed slice of model text; append in arrival order |
// | `tool_call` | `callId`, `turnId`, `name`, `args` | the agent invoked a tool |
// | `tool_result` | `callId`, `turnId`, `name`, `result` | a tool call returned |
// | `approval_request` | `callId`, `turnId`, `name`, `action`, `description` | the run paused for human approval; resolve via `POST /runs/{run}/approvals/{callId}/resolve` |
// | `usage` | `total` | cumulative token usage for the turn |
// | `done` | `turnId` | the turn finished; terminal frame of a message turn |
// | `error` | `message` | the turn ended abnormally |
// | `message` | the persisted message record | the per-run stream backfills history (one frame per stored message) on connect and resume |
// | `agent_event` | runner-specific | a normalized event from an external-agent (fanout) run |
// | `guidance_received` | runner-specific | mid-run operator guidance was applied |
//
// A chat turn typically streams `chunk`* then optional
// `tool_call`/`tool_result` pairs, an optional `usage`, and a final `done`.
// When the agent needs approval you get an `approval_request` followed by
// `done`; resolve the approval, then start the next turn.
type EventStream = string

// GuidanceRequest defines model for GuidanceRequest.
type GuidanceRequest struct {
	Text string `json:"text"`
}

// Message defines model for Message.
type Message struct {
	Content    *string    `json:"content,omitempty"`
	CreateTime *time.Time `json:"createTime,omitempty"`
	Id         string     `json:"id"`

	// Role One of: user, model, tool_call, tool_result, context, approval_request, approval_result (matches the messages.role CHECK constraint).
	Role string `json:"role"`

	// Sequence Monotonic per-run sequence; also the SSE resume id on the per-run events stream.
	Sequence *int `json:"sequence,omitempty"`
}

// MessageList defines model for MessageList.
type MessageList struct {
	Items         []Message `json:"items"`
	NextPageToken *string   `json:"nextPageToken,omitempty"`
}

// Poller Autotask ticket poller state.
type Poller struct {
	LastPolled    *time.Time `json:"lastPolled,omitempty"`
	SeenCount     *int       `json:"seenCount,omitempty"`
	WorkflowCount *int       `json:"workflowCount,omitempty"`
}

// Problem An RFC 9457 problem document, served as application/problem+json.
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// ResolveApprovalRequest defines model for ResolveApprovalRequest.
type ResolveApprovalRequest struct {
	Approved bool    `json:"approved"`
	Reason   *string `json:"reason,omitempty"`
}

// Run One execution, addressed by its stable sessions.id UUID.
type Run struct {
	// Agent Agent-task name for external/fanout runs; empty for chat and ticket runs.
	Agent      *string    `json:"agent,omitempty"`
	CreateTime *time.Time `json:"createTime,omitempty"`

	// Epoch Epoch counter; increments on each ContinueAsNew context rollover.
	Epoch *int `json:"epoch,omitempty"`

	// Id Stable run id (sessions.id); stable across epoch ContinueAsNew.
	Id openapi_types.UUID `json:"id"`

	// Kind Underlying session kind: chat, ticket, or monitor.
	Kind string `json:"kind"`

	// Parent Parent run id for fanout child runs; empty otherwise.
	Parent *string `json:"parent,omitempty"`

	// Status active, completed, or continued.
	Status string `json:"status"`

	// Strategy react = chat, step_dag = ticket triage, fanout/monitor = external agent.
	Strategy RunStrategy `json:"strategy"`

	// SupportedActions Sub-resources valid for this run. Gate UI on this; unsupported actions return 409. One or more of: messages, messages/retry, events, approvals, cancel, terminate, signal, guidance, policy, children.
	SupportedActions *[]string  `json:"supportedActions,omitempty"`
	UpdateTime       *time.Time `json:"updateTime,omitempty"`
}

// RunStrategy react = chat, step_dag = ticket triage, fanout/monitor = external agent.
type RunStrategy string

// RunList defines model for RunList.
type RunList struct {
	Items         []Run   `json:"items"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// SSETicket A short-lived single-use SSE ticket. Pass it once as ?ticket= on an SSE stream.
type SSETicket struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Ticket    string    `json:"ticket"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	Content string `json:"content"`
}

// SignalRequest defines model for SignalRequest.
type SignalRequest struct {
	Input *map[string]interface{} `json:"input,omitempty"`
	Name  string                  `json:"name"`
}

// TaskStateItem One row in the task_state ledger: the durable cross-run record of which
// candidates a task has handled and their outcome. task and candidateKey
// are opaque strings the deployment defines; outcome is opaque JSON the
// engine never interprets.
type TaskStateItem struct {
	// Attempts Case start count; guards infinite re-dispatch of failing candidates.
	Attempts *int `json:"attempts,omitempty"`

	// CandidateKey Deployment-defined dedup identity for a work item (e.g. an external record id).
	CandidateKey string `json:"candidateKey"`

	// CaseRunId Temporal run id of the Case workflow that claimed this candidate.
	CaseRunId  *string    `json:"caseRunId,omitempty"`
	CreateTime *time.Time `json:"createTime,omitempty"`

	// Outcome Arbitrary structured result recorded by the supervisor, passed through untouched. Any valid JSON value: an object, array, string, number, boolean, or null.
	Outcome *json.RawMessage `json:"outcome,omitempty"`

	// Status One of: in_progress, done, skipped, escalated, needs_attention.
	Status string `json:"status"`

	// Task The AgentConfig (task) name.
	Task       string     `json:"task"`
	UpdateTime *time.Time `json:"updateTime,omitempty"`
}

// TaskStateList defines model for TaskStateList.
type TaskStateList struct {
	Items         []TaskStateItem `json:"items"`
	NextPageToken *string         `json:"nextPageToken,omitempty"`
}

// WorkflowConfig defines model for WorkflowConfig.
type WorkflowConfig struct {
	Content *string `json:"content,omitempty"`
	Etag    *string `json:"etag,omitempty"`
	Name    string  `json:"name"`
}

// WorkflowConfigList defines model for WorkflowConfigList.
type WorkflowConfigList struct {
	Items         []WorkflowConfig `json:"items"`
	NextPageToken *string          `json:"nextPageToken,omitempty"`
}

// AgentTaskName defines model for AgentTaskName.
type AgentTaskName = string

// CallId defines model for CallId.
type CallId = string

// CandidateKey defines model for CandidateKey.
type CandidateKey = string

// ConfigName defines model for ConfigName.
type ConfigName = string

// LastEventId defines model for LastEventId.
type LastEventId = string

// PageSize defines model for PageSize.
type PageSize = int

// PageToken defines model for PageToken.
type PageToken = string

// RunId defines model for RunId.
type RunId = openapi_types.UUID

// SSETicketParam defines model for SSETicket.
type SSETicketParam = string

// TaskId defines model for TaskId.
type TaskId = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAgentTasksParams defines parameters for ListAgentTasks.
type ListAgentTasksParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// ListTaskStateParams defines parameters for ListTaskState.
type ListTaskStateParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`

	// Status Filter by status: in_progress, done, skipped, escalated, or needs_attention.
	Status *string `form:"status,omitempty" json:"status,omitempty"`
}

// GetEventsParams defines parameters for GetEvents.
type GetEventsParams struct {
	// SSETicketParam A short-lived single-use SSE ticket minted by POST /auth/sse-tickets.
	SSETicketParam *SSETicketParam `form:"ticket,omitempty" json:"ticket,omitempty"`

	// LastEventID Resume token; the server replays events after this sequence id.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// ListRunsParams defines parameters for ListRuns.
type ListRunsParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
	Strategy  *string    `form:"strategy,omitempty" json:"strategy,omitempty"`
	Status    *string    `form:"status,omitempty" json:"status,omitempty"`
	Kind      *string    `form:"kind,omitempty" json:"kind,omitempty"`
}

// ListRunApprovalsParams defines parameters for ListRunApprovals.
type ListRunApprovalsParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// ListRunChildrenParams defines parameters for ListRunChildren.
type ListRunChildrenParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// GetRunEventsParams defines parameters for GetRunEvents.
type GetRunEventsParams struct {
	// SSETicketParam A short-lived single-use SSE ticket minted by POST /auth/sse-tickets.
	SSETicketParam *SSETicketParam `form:"ticket,omitempty" json:"ticket,omitempty"`

	// LastEventID Resume token; the server replays events after this sequence id.
	LastEventID *LastEventId `json:"Last-Event-ID,omitempty"`
}

// ListRunMessagesParams defines parameters for ListRunMessages.
type ListRunMessagesParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// ListWorkflowConfigsParams defines parameters for ListWorkflowConfigs.
type ListWorkflowConfigsParams struct {
	PageSize  *PageSize  `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	PageToken *PageToken `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// PutWorkflowConfigParams defines parameters for PutWorkflowConfig.
type PutWorkflowConfigParams struct {
	// IfMatch The expected etag for optimistic concurrency.
	IfMatch *string `json:"If-Match,omitempty"`
}

// CreateRunJSONRequestBody defines body for CreateRun for application/json ContentType.
type CreateRunJSONRequestBody = CreateRunRequest

// ResolveRunApprovalJSONRequestBody defines body for ResolveRunApproval for application/json ContentType.
type ResolveRunApprovalJSONRequestBody = ResolveApprovalRequest

// SendRunGuidanceJSONRequestBody defines body for SendRunGuidance for application/json ContentType.
type SendRunGuidanceJSONRequestBody = GuidanceRequest

// SendRunMessageJSONRequestBody defines body for SendRunMessage for application/json ContentType.
type SendRunMessageJSONRequestBody = SendMessageRequest

// RetryRunMessageJSONRequestBody defines body for RetryRunMessage for application/json ContentType.
type RetryRunMessageJSONRequestBody = SendMessageRequest

// ExtendRunPolicyJSONRequestBody defines body for ExtendRunPolicy for application/json ContentType.
type ExtendRunPolicyJSONRequestBody = ApprovalPolicyDelta

// SetRunPolicyJSONRequestBody defines body for SetRunPolicy for application/json ContentType.
type SetRunPolicyJSONRequestBody = ApprovalPolicy

// SignalRunJSONRequestBody defines body for SignalRun for application/json ContentType.
type SignalRunJSONRequestBody = SignalRequest

// PutWorkflowConfigJSONRequestBody defines body for PutWorkflowConfig for application/json ContentType.
type PutWorkflowConfigJSONRequestBody = WorkflowConfig
